
DROP TABLE PROCEEDING_TBL;
DROP TABLE PROJECT_TBL;
DROP TABLE EMPLOYEE_TBL;
DROP TABLE DEPARTMENT_TBL;



--부모 
CREATE TABLE DEPARTMENT_TBL (
    DEPT_NO VARCHAR2(15 BYTE) NOT NULL,
    DEPT_NAME VARCHAR2(30 BYTE),
    DEPT_LOCATION VARCHAR2(50 BYTE),
    CONSTRAINT DE_NO PRIMARY KEY(DEPT_NO)
);

--자식
CREATE TABLE EMPLOYEE_TBL (
    EMP_NO NUMBER NOT NULL,
    DEPT_NO VARCHAR2(15 BYTE),
    POSITION CHAR(10 BYTE),
    NAME VARCHAR2(15 BYTE),
    HIRE_DATE DATE,
    SALARY NUMBER,
    CONSTRAINT EMPL_NO PRIMARY KEY(EMP_NO) ,
    CONSTRAINT EMPL_DE FOREIGN KEY(DEPT_NO) REFERENCES DEPARTMENT_TBL(DEPT_NO) ON DELETE SET NULL -- 부서가 삭제되면 사원들의 해당 부서 정보만 NULL처리한다.
);
-- 프로젝트 테이블 생성
CREATE TABLE PROJECT_TBL (
    PJT_NO NUMBER NOT NULL ,
    PJY_NAME VARCHAR2(30 BYTE),
    BEGIN_DATE DATE,
    END_DATE DATE,
    CONSTRAINT PRO_NO PRIMARY KEY(PJT_NO)
);

-- 프로젝트진행 테이블 생성
CREATE TABLE PROCEEDING_TBL (
    PJI_NO NUMBER NOT NULL,
    EMP_NO NUMBER ,
    PJT_NO NUMBER ,
    PJT_STATE NUMBER NOT NULL,
    CONSTRAINT PROC_NO PRIMARY KEY(PJI_NO),
    CONSTRAINT PROC_EMP FOREIGN KEY(EMP_NO) REFERENCES EMPLOYEE_TBL(EMP_NO)ON DELETE CASCADE,--사원이 삭제되면 프로젝트진행 명단에서 함께 삭제된다.
    CONSTRAINT PROC_PJT FOREIGN KEY(PJT_NO) REFERENCES PROJECT_TBL(PJT_NO) ON DELETE CASCADE --프로젝트가 삭제되면 프로젝트진행 명단에서 함께 삭제된다.
);